### ISSUE TITLE
Introduce Korean Reference Guide

### ISSUE THREAD

**Issue by ryukato** [AxonFramework/ReferenceGuide#23]
if I want to translate this docs, how can I name each files? can I give a name of file with language code at the end of the name like "architecture-overview-kr.md"?

**Comment by smcvb** [comment]
I think a different directory for the language you're implementing would be good approach.

By the way, thanks for offering to translate the reference guide to another language (guessing Korean if you add `kr` to the file name), but I don't want to ask you if we can expect a level of dedication on this.
We're not that versed in Korean, so any new additions we'd do to the Reference Guide would require an adjustment from your hand to fill the blanks. 
Do you have the time for that?

Additionally, an added disclaimer to point out that support of the other language comes from you as a contributor would help I'd assume.

Does the required commitment change your stance to providing a Korean version of the Reference Guide?

**Comment by ryukato** [comment]
I've been thinking the dedication and responsibility for the managing docs in Korean. 
Ok I will and can do that. 
And If I have something coming up and I can have time for providing Korean version of docs, then I will let you know.

I'm already doing some work on it so I will let you know when I am done the first version of translation.

**Comment by smcvb** [comment]
Great to hear you're willing to provide this @ryukato, much appreciated!
Looking forward to the Korean docs, even though I cant read them. :)

**Comment by ryukato** [comment]
I've done the first version of translation after 4 months work. :) 
But I need a migration my doc into this project and a way to check every things is working fine on my local.
So please let me know how to see things are working fine on my local.

**Comment by ryukato** [comment]
Closed by [PR#24](https://github.com/AxonFramework/ReferenceGuide/pull/24)
