### ISSUE TITLE
Provide Command/Event Interceptors Examples

### ISSUE THREAD

**Issue by m1l4n54v1c** [AxonFramework/ReferenceGuide#30]
- 3.1
Provide an example for defining interceptors in the documentation.

- 3.3
Provide additional information how to set up command interceptors in the Aggregate.

**Comment by smcvb** [comment]
This issue is resolved in #59

**Comment by smcvb** [comment]
Opened again as we'll add more documentation for this in 3.2

**Comment by smcvb** [comment]
Last issues resolved in [AxonIQ-Ref-Guide #23](https://github.com/AxonIQ/reference-guide/pull/23), hence closing.
