### ISSUE TITLE
Update existing Code Examples

### ISSUE THREAD

**Issue by smcvb** [AxonFramework/ReferenceGuide#37]
Take overall look on existing code samples.

Start example giving both Configuration API and Spring Boot configuration (if applicable).

Per default use the GiftCard domain in the code samples.

**Comment by abuijze** [comment]
For code samples in different styles (Spring Boot vs Configuration API), we should use the `codetabs` plugin for gitbook: https://github.com/GitbookIO/plugin-codetabs
