### ISSUE TITLE
Axon 3 PDF ref guide not searchable in OSX Preview

### ISSUE THREAD

**Issue by bliessens** [AxonFramework/ReferenceGuide#5]
Hi,

The PDF reference guide for Axon 2 is searchable from within OSX Preview application. The v3 ref guide however is not. 
Can this feature be restored?

**Comment by abuijze** [comment]
Hi Benoit,

the previous documentation was written in DocBook 5 (XML) and converted to HTML and PDF using the maven docbook plugin. That was a nightmare to configure and DocBook is not the nicest format to write in.

Markdown is a lot friendlier, and I am open to any converters to generate PDF etc. out of that. Right now, I am using GitBook for this, which is basically a service for generating books out of markdown.

So I am afraid that restoring this function involves more than I can currently foresee.

**Comment by bliessens** [comment]
Hi Allard,

I discovered the PDF is searchable with Adobe Acrobat. So maybe it's a OSX Preview issue after all.

Thanks for the update.

Cheers,
Benoît
