### ISSUE TITLE
Publish content as epub and/or pdf

### ISSUE THREAD

**Issue by abuijze** [AxonFramework/ReferenceGuide#61]
Some of our users wish to read the reference guide offline. It would be nice to be able to publish a static version of the documentation somewhere.

For sample code on how this could be done (for epub), see [epub.zip](https://github.com/AxonFramework/ReferenceGuide/files/2188978/epub.zip)

**Comment by smcvb** [comment]
Discussed the necessity of this ticket, which we've deemed quite low.
Will be closing this PR and issue for now as the requirement to provide an eBook is not overly evident at the moment.
