### ISSUE TITLE
Provide section which describes 'Distribution Considerations'

### ISSUE THREAD

**Issue by smcvb** [AxonFramework/ReferenceGuide#93]
This issue should introduce a new section under part four, which points out all the things users should think about when they want to run their Axon application in a distributed manner.
Think about:

- Distributing the commands bus - open source and AxonIQ approach.
- Setting your `RoutingStrategy` for command handling.
- Setting up a `RetryScheduler` in case commands cant be handled.
- Distributing event handling - open source and AxonIQ approach.
- Multi threading Tracking event handling.
- Setting your `SequencingPolicy` for event handling.
- How to deal with events from different applications in regards to de-/serialization.
- Distributed Queries caveat.

**Comment by m1l4n54v1c** [comment]
This issue is obsolete.
